# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123

  redis:
    host: 192.168.198.128
    port: 6379
    database: 0
    password: 123123


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8888

lzc:
  jwt:
    salt: f4e2e52034348f86b67cde581c0f9eb5
    expire: 7
    header: token

